config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  devise_for :users
  root to: "flats#index"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :flats, only: [:index, :show] do
    resources :reservations, only: [:create, :show] do
      member do
        get :confirm
        get :confirmed
      end
    end
    resources :bookings, only: [:create, :show]

    # Added correct routes for messages
    resources :messages, only: [:index, :new, :show, :create], param: :id do
      # This will ensure you're passing the correct params in URLs
    end

    # Route to view messages for a specific flat for the landlord (updated to avoid conflict)
    get 'messages_for_landlord', to: 'flats#messages', as: 'messages_for_landlord'
  end

  resources :questions, only: [:index, :create]

  resources :users, only: [:show, :edit, :update]  # Ensure 'update' is included here
  get 'profile', to: 'users#profile', as: 'profile'
  get 'edit_profile', to: 'users#edit', as: 'edit_user_profile'  # This is the added route for the edit page
  patch 'profile', to: 'users#update', as: 'update_user_profile'
  patch 'users/update_role', to: 'users#update_role', as: 'update_role'
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, :description, :price_per_night, :address, presence: true
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_neighbors :embedding
  after_create :set_embedding

  private

  def set_embedding
    client = OpenAI::Client.new
    response = client.embeddings(
      parameters: {
        model: 'text-embedding-3-small',
        input: "Flat: #{name}. Description: #{description}, Price per night: #{price_per_night}"
      }
    )
    embedding = response['data'][0]['embedding']
    update(embedding: embedding)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @flats = Flat.all.order(:id) # This ensures the flats are displayed in the same order as they were created.
  end

  def show
    @flat = Flat.find(params[:id])
    @user = @flat.user
    @booking = Booking.new # Add this line to prevent @booking from being nil
    @reservation = Reservation.new
    # Add coordinates for map display (geocoding happens for the specific flat)
    @markers = [{
      lat: @flat.latitude,
      lng: @flat.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {flat: @flat})
    }]
  end

  def messages
    @flat = Flat.find(params[:id]) # Find the flat by ID
    @messages = @flat.messages # Retrieve messages for that flat
  end

  private

  def flat_params
    params.require(:flat).permit(:photo, :name, :description, :amenities, :price_per_night, :address)
  end
end

app/views/flats/_info_window.html.erb
<!-- app/views/flats/_info_window.html.erb -->
<h2><%= flat.name %></h2>
<p><%= flat.address %></p>

app/views/flats/index.html.erb
<body class="index-page">
  <div class="cards">
    <% @flats.each do |flat| %>
      <div class="card-item">
        <% if flat.photo.attached? %>
          <%= link_to image_tag(flat.photo), flat_path(flat) %><br>
        <% end %>
        <strong><%= flat.name %></strong><br>
        <%= flat.address %> <br>
        <strong><%= flat.price_per_night %> gold per night</strong><br>
      </div>
    <% end %>
  </div>
</body>

app/views/flats/messages.html.erb
<!-- app/views/flats/messages.html.erb -->
<h1>Messages for <%= @flat.name %></h1>
<% @messages.each do |message| %>
  <div class="message">
    <strong>From: <%= message.sender.name %></strong>
    <p><%= message.content %></p>
    <small><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></small>
  </div>
<% end %>

app/views/flats/show.html.erb
<!-- Flat Details and Reservation Section Container -->
<div class="flat-container">
  <!-- Flat Details -->
  <div class="flat-image-wrapper">
    <h1><strong><%= @flat.name %></strong></h1>
    <% if @flat.photo.attached? %>
      <%= image_tag @flat.photo, class: 'flat-image' %>
    <% end %>
    <p></p>
    <p><%= @flat.description %></p>
    <!-- Thin line below description -->
    <hr class="thin-line0">
    <!-- Landlord picture and name -->
    <% if @user.photo.attached? %>
      <%= link_to user_path(@user), class: "no-decoration" do %>
        <div class="landlord-info">
          <%= image_tag @user.photo, class: 'landlord-image' %>
          <p>Hosted by <%= @user.name %></p>
        </div>
      <% end %>
    <% end %>
    <hr class="thin-line0">
    <!-- What this place offers section -->
    <h2><strong>What this place offers</strong></h2>
    <div class="amenities-grid">
      <div class="amenities-left">
        <% @flat.amenities.split(', ').first(@flat.amenities.split(', ').length / 2).each do |amenity| %>
          <div class="amenity-item">
            <span><%= amenity %></span>
          </div>
        <% end %>
      </div>
      <div class="amenities-right">
        <% @flat.amenities.split(', ').drop(@flat.amenities.split(', ').length / 2).each do |amenity| %>
          <div class="amenity-item">
            <span><%= amenity %></span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <!-- Reservation Section -->
  <div class="reservation-container" data-controller="reservation" data-reservation-price-per-night="<%= @flat.price_per_night %>">
    <h3><strong><%= @flat.price_per_night %> gold per night</strong></h3>
    <%= form_with model: @reservation, url: flat_reservations_path(@flat), local: true, html: { id: 'reservation-form' } do |f| %>
      <div class="form-group">
        <%= f.label :start_datetime, "CHECK-IN", style: "font-weight: bold; font-size: 0.8em;" %>
        <%= f.text_field :start_datetime,
          name: "reservation[start_datetime]",
          data: { controller: "datepicker", reservation_target: "startDatetime", action: "change->reservation#calculateTotal" },
          class: "form-control",
          id: "start_datetime" %>
      </div>
      <div class="form-group">
        <%= f.label :end_datetime, "CHECKOUT", style: "font-weight: bold; font-size: 0.8em;" %>
        <%= f.text_field :end_datetime,
          data: { controller: "datepicker", reservation_target: "endDatetime", action: "change->reservation#calculateTotal" },
          class: "form-control",
          id: "end_datetime" %>
      </div>
      <div class="form-group">
        <%= f.label :guests, "GUESTS", style: "font-weight: bold; font-size: 0.8em;" %>
        <%= f.number_field :guests,
          name: "reservation[guests]",
          data: { reservation_target: "guests", action: "input->reservation#calculateTotal" },
          class: "form-control",
          min: 1,
          id: "guests" %>
      </div>
      <div class="form-group">
        <%= f.submit "Reserve", class: "btn btn-primary w-100" %>
      </div>
      <p class="text-muted" style="font-size: 0.9em; text-align: center;">
        You won't be charged yet. <br>
        Price per night includes VAT and all applicable fees.
      </p>
      <div class="form-group">
        <!-- Price Breakdown -->
        <div class="d-flex justify-content-between">
          <p id="price-breakdown-msg" class="d-inline-block" data-reservation-target="priceBreakdown"></p>
          <p class="final-price-msg" data-reservation-target="finalPrice"></p>
        </div>
        <hr style="border-top: 1px solid #ccc; margin: 5px 0;">
        <div class="d-flex justify-content-between">
          <p><strong>Total</strong></p>
          <strong>
            <p class="final-price-msg" data-reservation-target="finalPrice"></p>
          </strong>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!-- Map -->
<div class="location">
  <h3><strong>Where you’ll be</strong></h3>
  <%= @flat.address %>
</div>
<div class="map-container"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>