config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  devise_for :users
  root to: "flats#index"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :flats, only: [:index, :show] do
    resources :reservations, only: [:create, :show] do
      member do
        get :confirm
        get :confirmed
      end
    end
    resources :bookings, only: [:create, :show]

    # Added correct routes for messages
    resources :messages, only: [:index, :new, :show, :create], param: :id do
      # This will ensure you're passing the correct params in URLs
    end

    # Route to view messages for a specific flat for the landlord (updated to avoid conflict)
    get 'messages_for_landlord', to: 'flats#messages', as: 'messages_for_landlord'
  end

  resources :questions, only: [:index, :create]

  resources :users, only: [:show, :edit, :update]  # Ensure 'update' is included here
  get 'profile', to: 'users#profile', as: 'profile'
  get 'edit_profile', to: 'users#edit', as: 'edit_user_profile'  # This is the added route for the edit page
  patch 'profile', to: 'users#update', as: 'update_user_profile'
  patch 'users/update_role', to: 'users#update_role', as: 'update_role'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon with-bottom-border">
  <div class="container-fluid">
    <%= link_to flats_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dadymzua9/image/upload/v1/logo_zysezj" %>
    <% end %>
    <% if (controller_name == "messages" && action_name == "new" && @flat.present? && @flat.user.photo.attached?) || (controller_name == "reservations" && action_name == "confirmed" && @reservation.flat.present? && @reservation.flat.user.photo.attached?) %>
      <% if controller_name == "messages" && action_name == "new" %>
        <%= link_to user_path(@flat.user), class: "navbar-brand-big" do %>
          <%= image_tag @flat.user.photo, alt: "Landlord Profile Picture" %>
        <% end %>
      <% elsif controller_name == "reservations" && action_name == "confirmed" %>
        <%= link_to user_path(@reservation.flat.user), class: "navbar-brand-big" do %>
          <%= image_tag @reservation.flat.user.photo, alt: "Landlord Profile Picture" %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to questions_path, class: "navbar-brand-big" do %>
        <%= image_tag "https://res.cloudinary.com/dadymzua9/image/upload/v1/Chatbot_Fizwick_Goldgrin_xbjqhn", alt: "Default Brand Logo" %>
      <% end %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= image_tag current_user.photo, class: "avatar-large", alt: "User Avatar" %>
              <% else %>
                <%= image_tag "https://res.cloudinary.com/dadymzua9/image/upload/v1/avatar_placeholder_gadz4b", class: "avatar-large", alt: "Default User Avatar" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>